[tools]
rust = "nightly"
"cargo:wasm-pack" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:https://github.com/cksac/fake-rs" = { version = "latest", features = "cli" }
python = "latest"

[tasks.fetch-test-data]
run = [
    "curl -L https://www.kaggle.com/api/v1/datasets/download/olistbr/brazilian-ecommerce -o test_data/olist/olist.zip",
    "unzip -o test_data/olist/olist.zip -d test_data/olist",
    "rm test_data/olist/olist.zip",
]

[tasks.build-web]
description = "Build WASM package for web target"
dir = "node"
run = [
    "echo 'Building WASM package for web target...'",
    "wasm-pack build --target web --out-dir pkg --scope arlyon"
]
